### ISSUE TITLE
字下げが行われない

### ISSUE THREAD

**Issue by eliza0x** [oithxs/club_magazine#16]
turai

**Comment by odanado** [comment]
`\parindent = 10pt` と指定すると字下げされることを確認しました
http://www.biwako.shiga-u.ac.jp/sensei/kumazawa/tex/048.html

**Comment by odanado** [comment]
`\usepackage{indentfirst}` はセクションの直後の段落を字下げするかどうかなので，不要です

**Comment by odanado** [comment]
あっこっちでは #17
